/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: Ddiaz Design (https://sketchfab.com/ddiaz-design)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/2003-mercedes-benz-e55-amg-w211-487de3f923784dfa8a8ac013e36b0955
Title: 2003 Mercedes-Benz E55 AMG W211
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-0.759, -0.616, 1.346]} scale={0.001}>
          <mesh geometry={nodes.Mesh1_Plas_Leth_Int_0.geometry} material={materials.Plas_Leth_Int} />
          <mesh geometry={nodes.Mesh1_Black_plastic_0.geometry} material={materials.Black_plastic} />
          <mesh geometry={nodes.Mesh1_material_SS_0.geometry} material={materials.material_SS} />
          <mesh geometry={nodes.Mesh1_plastic_Int_0.geometry} material={materials.plastic_Int} />
          <mesh geometry={nodes.Mesh1_Chorme_0.geometry} material={materials.Chorme} />
          <mesh geometry={nodes.Mesh1_METAL_0.geometry} material={materials.METAL} />
          <mesh geometry={nodes.Mesh1_display_1_0.geometry} material={materials.display_1} />
          <mesh geometry={nodes.Mesh1_screen_0.geometry} material={materials.screen} />
          <mesh geometry={nodes.Mesh1_tachometer__spec1_0.geometry} material={materials.tachometer__spec1} />
          <mesh geometry={nodes.Mesh2_Plas_Leth_Int_0.geometry} material={materials.Plas_Leth_Int} />
          <mesh geometry={nodes.Mesh3_Light_Chrome_0.geometry} material={materials.Light_Chrome} />
          <mesh geometry={nodes.Mesh3_CarPaint_0.geometry} material={materials.CarPaint} />
          <mesh geometry={nodes.Mesh3_EXT_Plastic_0.geometry} material={materials.EXT_Plastic} />
          <mesh geometry={nodes.Mesh3_Plastic_SH_0.geometry} material={materials.Plastic_SH} />
          <mesh geometry={nodes.Mesh3_Black_plastic_0.geometry} material={materials.Black_plastic} />
          <mesh geometry={nodes.Mesh3_LIGHT_SMAL_0.geometry} material={materials.LIGHT_SMAL} />
          <mesh geometry={nodes.Mesh4_Glass_0.geometry} material={materials.Glass} />
          <mesh geometry={nodes.Mesh5_Red_glass_0.geometry} material={materials.Red_glass} />
          <mesh geometry={nodes.Mesh6_Glass_0.geometry} material={materials.Glass} />
          <mesh geometry={nodes.Mesh7_Red_glass_0.geometry} material={materials.Red_glass} />
          <mesh geometry={nodes.Mesh8_Glass_0.geometry} material={materials.Glass} />
          <mesh geometry={nodes.Mesh9_Glass_0.geometry} material={materials.Glass} />
          <mesh geometry={nodes.Mesh10_Glass_0.geometry} material={materials.Glass} />
          <mesh geometry={nodes.Mesh11_inner_glass_0.geometry} material={materials.inner_glass} />
          <mesh geometry={nodes.Mesh11_Glass_0.geometry} material={materials.Glass} />
          <mesh geometry={nodes.Mesh11_Plas_Leth_Int_0.geometry} material={materials.Plas_Leth_Int} />
          <mesh geometry={nodes.Mesh11_Black_plastic_0.geometry} material={materials.Black_plastic} />
          <mesh geometry={nodes.Mesh11_grille_0.geometry} material={materials.grille} />
          <mesh geometry={nodes.Mesh11_CarPaint_0.geometry} material={materials.CarPaint} />
          <mesh geometry={nodes.Mesh11_RIM_MAT_0.geometry} material={materials.RIM_MAT} />
          <mesh geometry={nodes.Mesh12_CarPaint_0.geometry} material={materials.CarPaint} />
          <mesh geometry={nodes.Mesh12_Chorme_0.geometry} material={materials.Chorme} />
          <mesh geometry={nodes.Mesh12_Plastic_SH_0.geometry} material={materials.Plastic_SH} />
          <mesh geometry={nodes.Mesh12_engine_Mat_0.geometry} material={materials.engine_Mat} />
          <mesh geometry={nodes.Mesh12_Black_plastic_0.geometry} material={materials.Black_plastic} />
          <mesh geometry={nodes.Mesh13_Chorme_0.geometry} material={materials.Chorme} />
          <mesh geometry={nodes.Mesh13_Light_Chrome_0.geometry} material={materials.Light_Chrome} />
          <mesh geometry={nodes.Mesh13_CarPaint_0.geometry} material={materials.CarPaint} />
          <mesh geometry={nodes.Mesh13_Plas_Leth_Int_0.geometry} material={materials.Plas_Leth_Int} />
          <mesh geometry={nodes.Mesh14_CarPaint_0.geometry} material={materials.CarPaint} />
          <mesh geometry={nodes.Mesh14_Light_Chrome_0.geometry} material={materials.Light_Chrome} />
          <mesh geometry={nodes.Mesh14_Plastic_SH_0.geometry} material={materials.Plastic_SH} />
          <mesh geometry={nodes.Mesh14_Black_plastic_0.geometry} material={materials.Black_plastic} />
          <mesh geometry={nodes.Mesh14_Chorme_0.geometry} material={materials.Chorme} />
          <mesh geometry={nodes.Mesh14_LIGHT_SMAL_0.geometry} material={materials.LIGHT_SMAL} />
          <mesh geometry={nodes.Mesh15_CarPaint_0.geometry} material={materials.CarPaint} />
          <mesh geometry={nodes.Mesh15_Plastic_SH_0.geometry} material={materials.Plastic_SH} />
          <mesh geometry={nodes.Mesh15_Light_Chrome_0.geometry} material={materials.Light_Chrome} />
          <mesh geometry={nodes.Mesh15_Chorme_0.geometry} material={materials.Chorme} />
          <mesh geometry={nodes.Mesh15_Black_plastic_0.geometry} material={materials.Black_plastic} />
          <mesh geometry={nodes.Mesh16_Chorme_0.geometry} material={materials.Chorme} />
          <mesh geometry={nodes.Mesh16_engine_Mat_0.geometry} material={materials.engine_Mat} />
          <mesh geometry={nodes.Mesh16_CarPaint_0.geometry} material={materials.CarPaint} />
          <mesh geometry={nodes.Mesh16_METAL_0.geometry} material={materials.METAL} />
          <mesh geometry={nodes.Mesh16_Black_plastic_0.geometry} material={materials.Black_plastic} />
          <mesh geometry={nodes.Mesh16_Plastic_SH_0.geometry} material={materials.Plastic_SH} />
          <mesh geometry={nodes.Mesh17_Chorme_0.geometry} material={materials.Chorme} />
          <mesh geometry={nodes.Mesh17_CarPaint_0.geometry} material={materials.CarPaint} />
          <mesh geometry={nodes.Mesh17_Plas_Leth_Int_0.geometry} material={materials.Plas_Leth_Int} />
          <mesh geometry={nodes.Mesh17_material_SS_0.geometry} material={materials.material_SS} />
          <mesh geometry={nodes.Mesh17_Glass_0.geometry} material={materials.Glass} />
          <mesh geometry={nodes.Mesh17_Plastic_SH_0.geometry} material={materials.Plastic_SH} />
          <mesh geometry={nodes.Mesh17_Light_Chrome_0.geometry} material={materials.Light_Chrome} />
          <mesh geometry={nodes.Mesh18_Plas_Leth_Int_0.geometry} material={materials.Plas_Leth_Int} />
          <mesh geometry={nodes.Mesh18_CarPaint_0.geometry} material={materials.CarPaint} />
          <mesh geometry={nodes.Mesh18_material_SS_0.geometry} material={materials.material_SS} />
          <mesh geometry={nodes.Mesh18_Plastic_SH_0.geometry} material={materials.Plastic_SH} />
          <mesh geometry={nodes.Mesh18_Chorme_0.geometry} material={materials.Chorme} />
          <mesh geometry={nodes.Mesh18_Light_Chrome_0.geometry} material={materials.Light_Chrome} />
          <mesh geometry={nodes.Mesh18_Glass_0.geometry} material={materials.Glass} />
          <mesh geometry={nodes.Mesh19_CarPaint_0.geometry} material={materials.CarPaint} />
          <mesh geometry={nodes.Mesh19_Chorme_0.geometry} material={materials.Chorme} />
          <mesh geometry={nodes.Mesh19_Light_Chrome_0.geometry} material={materials.Light_Chrome} />
          <mesh geometry={nodes.Mesh19_Plas_Leth_Int_0.geometry} material={materials.Plas_Leth_Int} />
          <mesh geometry={nodes.Mesh19_Plastic_SH_0.geometry} material={materials.Plastic_SH} />
          <mesh geometry={nodes.Mesh19_material_SS_0.geometry} material={materials.material_SS} />
          <mesh geometry={nodes.Mesh19_Black_plastic_0.geometry} material={materials.Black_plastic} />
          <mesh geometry={nodes.Mesh19_Glass_0.geometry} material={materials.Glass} />
          <mesh geometry={nodes.Mesh20_Red_glass_0.geometry} material={materials.Red_glass} />
          <mesh geometry={nodes.Mesh21_Engine_Mat_2_0.geometry} material={materials.Engine_Mat_2} />
          <mesh geometry={nodes.Mesh21_Black_plastic_0.geometry} material={materials.Black_plastic} />
          <mesh geometry={nodes.Mesh21_Light_Chrome_0.geometry} material={materials.Light_Chrome} />
          <mesh geometry={nodes.Mesh21_METAL_0.geometry} material={materials.METAL} />
          <mesh geometry={nodes.Mesh22_Glass_0.geometry} material={materials.Glass} />
          <mesh geometry={nodes.Mesh23_Chorme_0.geometry} material={materials.Chorme} />
          <mesh geometry={nodes.Mesh23_CarPaint_0.geometry} material={materials.CarPaint} />
          <mesh geometry={nodes.Mesh23_Light_Chrome_0.geometry} material={materials.Light_Chrome} />
          <mesh geometry={nodes.Mesh23_Plas_Leth_Int_0.geometry} material={materials.Plas_Leth_Int} />
          <mesh geometry={nodes.Mesh23_Plastic_SH_0.geometry} material={materials.Plastic_SH} />
          <mesh geometry={nodes.Mesh23_material_SS_0.geometry} material={materials.material_SS} />
          <mesh geometry={nodes.Mesh23_Glass_0.geometry} material={materials.Glass} />
          <mesh geometry={nodes.Mesh23_Black_plastic_0.geometry} material={materials.Black_plastic} />
          <mesh geometry={nodes.Mesh24_CarPaint_0.geometry} material={materials.CarPaint} />
          <mesh geometry={nodes.Mesh25_Plas_Leth_Int_0.geometry} material={materials.Plas_Leth_Int} />
          <mesh geometry={nodes.Mesh26_Plas_Leth_Int_0.geometry} material={materials.Plas_Leth_Int} />
          <mesh geometry={nodes.Mesh28_Plas_Leth_Int_0.geometry} material={materials.Plas_Leth_Int} />
          <mesh geometry={nodes.Mesh29_CarPaint_0.geometry} material={materials.CarPaint} />
          <mesh geometry={nodes.Mesh30_Light_Chrome_0.geometry} material={materials.Light_Chrome} />
          <mesh geometry={nodes.Mesh31_Plas_Leth_Int_0.geometry} material={materials.Plas_Leth_Int} />
          <mesh geometry={nodes.Mesh31_Black_plastic_0.geometry} material={materials.Black_plastic} />
          <mesh geometry={nodes.Mesh31_METAL_0.geometry} material={materials.METAL} />
          <mesh geometry={nodes.Mesh31_material_SS_0.geometry} material={materials.material_SS} />
          <mesh geometry={nodes.Mesh31_EXT_Plastic_0.geometry} material={materials.EXT_Plastic} />
          <mesh geometry={nodes.Mesh32__Snow_1_0.geometry} material={materials.Snow_1} />
          <mesh geometry={nodes.Mesh32__Charcoal_1_0.geometry} material={materials.Charcoal_1} />
          <mesh geometry={nodes.Mesh32_METAL_0.geometry} material={materials.METAL} />
          <mesh geometry={nodes.Mesh33_METAL_0.geometry} material={materials.METAL} />
          <mesh geometry={nodes.Mesh33_Black_plastic_0.geometry} material={materials.Black_plastic} />
          <mesh geometry={nodes.Mesh33__Black_1_0.geometry} material={materials.Black_1} />
          <mesh geometry={nodes.Mesh33__Color_A01_3_0.geometry} material={materials.Color_A01_3} />
          <mesh geometry={nodes.Mesh33_Chorme_0.geometry} material={materials.Chorme} />
          <mesh geometry={nodes.Mesh34_Tire_0.geometry} material={materials.Tire} />
          <mesh geometry={nodes.Mesh35__Charcoal_1_0.geometry} material={materials.Charcoal_1} />
          <mesh geometry={nodes.Mesh35_Chorme_0.geometry} material={materials.Chorme} />
          <mesh geometry={nodes.Mesh35_RIM_MAT_0.geometry} material={materials.RIM_MAT} />
          <mesh geometry={nodes.Mesh35_Tire_0.geometry} material={materials.Tire} />
          <mesh geometry={nodes.Mesh36__Snow_1_0.geometry} material={materials.Snow_1} />
          <mesh geometry={nodes.Mesh36__Charcoal_1_0.geometry} material={materials.Charcoal_1} />
          <mesh geometry={nodes.Mesh36_METAL_0.geometry} material={materials.METAL} />
          <mesh geometry={nodes.Mesh37_METAL_0.geometry} material={materials.METAL} />
          <mesh geometry={nodes.Mesh37_Black_plastic_0.geometry} material={materials.Black_plastic} />
          <mesh geometry={nodes.Mesh37__Black_1_0.geometry} material={materials.Black_1} />
          <mesh geometry={nodes.Mesh37__Color_A01_3_0.geometry} material={materials.Color_A01_3} />
          <mesh geometry={nodes.Mesh37_Chorme_0.geometry} material={materials.Chorme} />
          <mesh geometry={nodes.Mesh38_Tire_0.geometry} material={materials.Tire} />
          <mesh geometry={nodes.Mesh39__Charcoal_1_0.geometry} material={materials.Charcoal_1} />
          <mesh geometry={nodes.Mesh39_Chorme_0.geometry} material={materials.Chorme} />
          <mesh geometry={nodes.Mesh39_RIM_MAT_0.geometry} material={materials.RIM_MAT} />
          <mesh geometry={nodes.Mesh39_Tire_0.geometry} material={materials.Tire} />
          <mesh geometry={nodes.Mesh40__Snow_1_0.geometry} material={materials.Snow_1} />
          <mesh geometry={nodes.Mesh40__Charcoal_1_0.geometry} material={materials.Charcoal_1} />
          <mesh geometry={nodes.Mesh40_METAL_0.geometry} material={materials.METAL} />
          <mesh geometry={nodes.Mesh41_METAL_0.geometry} material={materials.METAL} />
          <mesh geometry={nodes.Mesh41_Black_plastic_0.geometry} material={materials.Black_plastic} />
          <mesh geometry={nodes.Mesh41__Black_1_0.geometry} material={materials.Black_1} />
          <mesh geometry={nodes.Mesh41__Color_A01_3_0.geometry} material={materials.Color_A01_3} />
          <mesh geometry={nodes.Mesh41_Chorme_0.geometry} material={materials.Chorme} />
          <mesh geometry={nodes.Mesh42_Tire_0.geometry} material={materials.Tire} />
          <mesh geometry={nodes.Mesh43__Charcoal_1_0.geometry} material={materials.Charcoal_1} />
          <mesh geometry={nodes.Mesh43_Chorme_0.geometry} material={materials.Chorme} />
          <mesh geometry={nodes.Mesh43_RIM_MAT_0.geometry} material={materials.RIM_MAT} />
          <mesh geometry={nodes.Mesh43_Tire_0.geometry} material={materials.Tire} />
          <mesh geometry={nodes.Mesh44__Snow_1_0.geometry} material={materials.Snow_1} />
          <mesh geometry={nodes.Mesh44__Charcoal_1_0.geometry} material={materials.Charcoal_1} />
          <mesh geometry={nodes.Mesh44_METAL_0.geometry} material={materials.METAL} />
          <mesh geometry={nodes.Mesh45_METAL_0.geometry} material={materials.METAL} />
          <mesh geometry={nodes.Mesh45_Black_plastic_0.geometry} material={materials.Black_plastic} />
          <mesh geometry={nodes.Mesh45__Black_1_0.geometry} material={materials.Black_1} />
          <mesh geometry={nodes.Mesh45__Color_A01_3_0.geometry} material={materials.Color_A01_3} />
          <mesh geometry={nodes.Mesh45_Chorme_0.geometry} material={materials.Chorme} />
          <mesh geometry={nodes.Mesh46_Tire_0.geometry} material={materials.Tire} />
          <mesh geometry={nodes.Mesh47__Charcoal_1_0.geometry} material={materials.Charcoal_1} />
          <mesh geometry={nodes.Mesh47_Chorme_0.geometry} material={materials.Chorme} />
          <mesh geometry={nodes.Mesh47_RIM_MAT_0.geometry} material={materials.RIM_MAT} />
          <mesh geometry={nodes.Mesh47_Tire_0.geometry} material={materials.Tire} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
